### ISSUE TITLE
Example Configuration

### ISSUE THREAD

**Issue by stcktrce** [j-selby/liftpush#1]
Hello!

Would you mind adding, or publishing some form of an example for the configuration so others can use this without having to dive trough the source to figure out how the `config.toml` should look like?

Cheers

**Comment by j-selby** [comment]
Hi!

Sorry, I hadn't intended on making this public yet - wanted to do some cleanup/auditing. I'll add documentation/whatever at some point to the main repo.

Example config file would look like the following (config.toml):

```toml
bind_addr = "localhost:8000"
external_url = "https://p.jselby.net/"
base_path = "saved/"
key = "<random sequence of characters, plaintext>"

# The stuff you use in ShareX or curl - upload only
[[api_keys]]
key = "<random sequence of characters, plaintext>"
comment = "This is my desktop's key"

# For the web UI - can delete/view everything, so should be a little more secure
[[users]]
username = "selby"
password = "<sha3 256 bit hash of password>"
```

I'll leave this open as a reminder to add documentation.
